version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
    container_name: larascript-node-frontend
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN=larascriptnode.com
      - EMAIL=ben.shepherd@gmx.com

volumes:
  letsencrypt:
