version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: larascript-node-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf