version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DOMAIN=${DOMAIN:-larascriptnode.com}
        - EMAIL=${EMAIL:-ben.shepherd@gmx.com}
    container_name: larascript-node-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN:-larascriptnode.com}
      - EMAIL=${EMAIL:-ben.shepherd@gmx.com}

volumes:
  letsencrypt: